-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  role text check (role in ('admin', 'staff')) default 'staff',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for skills
create table skills (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table skills enable row level security;

create policy "Skills are viewable by everyone." on skills
  for select using (true);

create policy "Only admins can insert skills." on skills
  for insert with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Only admins can update skills." on skills
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Only admins can delete skills." on skills
  for delete using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for user skills (Many-to-Many)
create table user_skills (
  user_id uuid references profiles(id) on delete cascade not null,
  skill_id bigint references skills(id) on delete cascade not null,
  primary key (user_id, skill_id)
);

alter table user_skills enable row level security;

create policy "User skills are viewable by everyone." on user_skills
  for select using (true);

create policy "Only admins can manage user skills." on user_skills
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for time slots
create table time_slots (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g., "A枠", "16-21"
  start_time time not null,
  end_time time not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table time_slots enable row level security;

create policy "Time slots are viewable by everyone." on time_slots
  for select using (true);

create policy "Only admins can manage time slots." on time_slots
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for shift requests
create table shift_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date date not null,
  time_slot_id bigint references time_slots(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, date, time_slot_id)
);

alter table shift_requests enable row level security;

create policy "Users can view their own requests." on shift_requests
  for select using (auth.uid() = user_id);

create policy "Admins can view all requests." on shift_requests
  for select using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Users can insert their own requests." on shift_requests
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own requests." on shift_requests
  for delete using (auth.uid() = user_id);

-- Create a table for shift assignments (Final schedule)
create table shift_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date date not null,
  time_slot_id bigint references time_slots(id) on delete cascade not null,
  task text, -- Optional: assigned task/position
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, date, time_slot_id)
);

alter table shift_assignments enable row level security;

create policy "Assignments are viewable by everyone." on shift_assignments
  for select using (true);

create policy "Only admins can manage assignments." on shift_assignments
  for all using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'staff');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
